app/census/views.py
from __future__ import division
import operator
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, json, jsonify, current_app)
from flask.ext.login import (login_user, logout_user, current_user)
from flask.ext.principal import Identity, AnonymousIdentity, identity_changed

from sqlalchemy import create_engine
from sqlalchemy.sql import select, func, and_
from sqlalchemy.sql.expression import tuple_

from app import db
from config import SQLALCHEMY_DATABASE_URI
from app.users.models import Users, Roles
from app.census.datahelpers import build_table

mod = Blueprint('census', __name__, url_prefix='/census')


@mod.before_request
def before_request():
    g.conn = create_engine(SQLALCHEMY_DATABASE_URI)
    g.t = None
    g.t = build_table('census')


@mod.route('', methods=['GET', ])
def census():
    income_districts = []
    poverty_districts = []
    medianincome_districts = []
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'INCOME').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        income_districts.append(district)
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'POVERTY').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        poverty_districts.append(district)
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'MEDIANINCOME').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        medianincome_districts.append(district)
    
    return render_template('census/index.html', income_districts=income_districts, poverty_districts=poverty_districts, medianincome_districts=medianincome_districts)


@mod.route('/test', methods=['GET', ])
def census_test():
    values = {}
    s = select(
        [
            g.t.c.type,
            g.t.c.district,
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], g.t.c.race != 'ALL').group_by(
            g.t.c.type,
            g.t.c.district,
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.type,
                g.t.c.district,
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for result in results:
        type = getattr(result, 'type')
        if not values.get(type):
            values[type] = {}
        district = getattr(result, 'district')
        if not values[type].get(district):
            values[type][district] = {}
        race = getattr(result, 'race')
        if not values[type][district].get(race):
            if getattr(result, 'summed'):
                values[type][district][race] = {}
        if getattr(result, 'summed'):
            values[type][district][race] = getattr(result, 'summed')

    return render_template('census/test.html', values=values)


@mod.route('/poverty_json', methods=['GET', ])
def census_poverty_json():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return_val = {
        'values': values,
        'graph_name': 'Poverty % by Race in All Districts',
        'url': url_for('census.census_poverty_json', _external=True)
    }
    return jsonify(return_val)


@mod.route('/poverty', methods=['GET', ])
def census_proverty():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/poverty.html', values=values)


@mod.route('/poverty_by_district/<district_name>', methods=['GET', ])
def census_proverty_by_district(district_name):
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.district == district_name,
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/poverty_by_district.html', values=values, district=district_name)


@mod.route('/income_by_district/<district_name>', methods=['GET', ])
def census_income_by_district(district_name):
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(
            and_(
                g.t.c.type == 'INCOME',
                g.t.c.district == district_name,
                g.t.c.value != 0,
                g.t.c.race == 'ALL',
            )
        ).group_by(
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    total_value = 0
    for value in results:
        total_value = total_value + getattr(value, 'summed')
        factor = getattr(value, 'factor')
        values[factor] = {'count': value.summed}

    for key in values:
        if total_value > 0:
                values[key]['percent'] = round((values[key]['count'] / values['ALL']['count']) * 100, 2)
    values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/income_by_district.html', values=values, district=district_name)


@mod.route('/income', methods=['GET', ])
def census_income():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(
            and_(
                g.t.c.type == 'INCOME',
                g.t.c.value != 0,
                g.t.c.race == 'ALL',
            )
        ).group_by(
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    total_value = 0
    for value in results:
        total_value = total_value + getattr(value, 'summed')
        factor = getattr(value, 'factor')
        values[factor] = {'count': value.summed}

    for key in values:
        print
        if total_value > 0:

app/templates/census/education_bygender.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Gender</th>
        <th>EDU Level</th>
        <th>Count</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        {% for job in value %}
        <tr>
            {% if loop.first %}
            <td rowspan="{{ value|length }}"><div class="text-right">{{ key }}</div></td>
            {% endif %} 
            <td><div class="text-right">{{ job }}</div></td>
            <td><div class="text-right">{{ value[job]|comma_format }}</div></td>
        </tr>
        {% endfor %}
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Education in {% if district %}{{ district }}{% else %}Davidson County{% endif %}'
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Count'
            },
        },
        series: [
            {
                name: 'MALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['MALE'] }},
                            {% endfor %}
                      ]
            },
            {
                name: 'FEMALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['FEMALE'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/income.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Income Range</th>
        <th>Count</th>
        <th>% Total</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        <tr>
            <td><div class="text-right">{{ key }}</div></td>
            <td><div class="text-right">{{ value['count']|comma_format }}</div></td>
            <td><div class="text-right">{{ value['percent'] }}%</div></td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Income Bracket in Davidson County'
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Percentage'
            },
        },
        series: [
            {
                name: '% total for bracket',
                      data: [
                            {% for key, value in values %}
                            {{ value['percent'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/income_by_district.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Income Range</th>
        <th>Count</th>
        <th>% Total</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        <tr>
            <td><div class="text-right">{{ key }}</div></td>
            <td><div class="text-right">{{ value['count']|comma_format }}</div></td>
            <td><div class="text-right">{{ value['percent'] }}%</div></td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Income Bracket in {{ district }}'
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Percentage'
            },
        },
        series: [
            {
                name: '% total for bracket',
                      data: [
                            {% for key, value in values %}
                            {{ value['percent'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/index.html
{% extends 'base.html' %}
{% block content %}
<!--=============== HEADER ===============-->

    <div class="container">
    <header>
      <div class="row">
        <div class="span7">
          <h1>Diversity</h1>

<br />
          <strong>
            <h2>
              Nashville:
<br />
              Growing Diversity and Inclusivity
            </h2>
          </strong>
            <p>
              In his 2013 State of the City Address, Mayor Karl Dean, said this: “Successful cities are cities with a high quality of life for people at all points on the economic spectrum. Successful cities are cities that offer opportunity to not just the well-educated, but everyone with the desire to have a better life.”
<br />
<br />
              We know that Nashville and Davidson County is racially, ethnically, and culturally—and growing more so each year—but what demographic statistics don’t tell us is whether our diversity also correlates with an experience of inclusion among the many cultural groups that call Nashville home.
<br/>
<br/>
        </div>
        <div class="span1">
        </div>
        <div class="span4">
          <a href="http://www.nashville.gov/Human-Relations-Commission.aspx" target="_blank">
              <img src="{{ url_for('static', filename='img/MHRCLogoFinal.jpg') }}" alt="Nashville Human Relations Commission" />
          </a>
        </div>
      </div><!-- /.row -->
    </header>
    </div><!-- /.container -->

    <div class="container">
      <div class="row">

        <div class="span12">
          <h2>Data Overview</h2>
            <p>
            This data was pulled from the American Community Survey.
            </p>
        </div>

      </div><!-- /.row -->
    </div><!-- /.container -->
<!--=============== Data Overview ===============-->


<!--=============== ACCORDIAN, DATA ===============-->

<br />

    <div class="container">
      <div class="row">

        <div class="span1">
        </div>

        <div class="span10">
          <div class="accordion" id="accordion2">

            <!--=============== Poverty ===============-->
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                  <h3>
                    Poverty
                  </h3>
                </a>
              </div>
                <div id="collapseOne" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      We know that Nashville and Davidson County is racially, ethnically, and culturally—and growing more so each year—but what demographic statistics don’t tell us is whether our diversity also correlates with an experience of inclusion among the many cultural groups that call Nashville home.
                    </p>
                    <ul>
                        <li><a href="{{url_for('census.census_proverty')}}">County Wide</a>
                        {% for report in income_districts%}
                        <li><a href="{{url_for('census.census_proverty_by_district', district_name=report[0]) }}">{{report[0]}}</a>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>

            <!--=============== Household Income ===============-->
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                  <h3>
                    Household Income
                  </h3>
                </a>
              </div>
                <div id="collapseTwo" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                      We know that Nashville and Davidson County is racially, ethnically, and culturally—and growing more so each year—but what demographic statistics don’t tell us is whether our diversity also correlates with an experience of inclusion among the many cultural groups that call Nashville home.
                    </p>
                    <ul>
                        <li><a href="{{url_for('census.census_income')}}">County Wide</a>
                        {% for report in income_districts%}
                        <li><a href="{{url_for('census.census_income_by_district', district_name=report[0]) }}">{{report[0]}}</a>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>
            <!--=============== Median Income ===============-->
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                  <h3>
                    Median Income
                  </h3>
                </a>
              </div>
                <div id="collapseThree" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    </p>
                    <ul>
                        <li><a href="{{url_for('census.census_medianincome')}}">County Wide</a>
                        {% for report in income_districts%}
                        <li><a href="{{url_for('census.census_medianincome_by_district', district_name=report[0]) }}">{{report[0]}}</a>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>
            <!--=============== Occupational Counts ===============-->
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                  <h3>
                    Occupational Counts
                  </h3>
                </a>
              </div>
                <div id="collapseFour" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    </p>
                    <ul>
                        <li><a href="{{url_for('census.census_occupation_bygender')}}">County Wide</a>
                        {% for report in income_districts%}
                        <li><a href="{{url_for('census.census_occupation_bygender_by_district', district_name=report[0]) }}">{{report[0]}}</a>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>
            <!--=============== Occupational Counts ===============-->
            <div class="accordion-group">
              <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                  <h3>
                    Educational Levels
                  </h3>
                </a>
              </div>
                <div id="collapseFive" class="accordion-body collapse">
                  <div class="accordion-inner">
                    <p>
                    </p>
                    <ul>
                        <li><a href="{{url_for('census.census_education_bygender')}}">County Wide</a>
                        {% for report in income_districts%}
                        <li><a href="{{url_for('census.census_education_bygender_by_district', district_name=report[0]) }}">{{report[0]}}</a>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
            </div>

          </div><!-- /#accordion2 -->
        </div><!-- /.span10 -->

        <div class="span1">
        </div>

      </div><!-- /.row -->
    </div><!-- /.container -->
{% endblock %}

app/templates/census/medianincome.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Income Range</th>
        <th>Count</th>
        <th>% Total</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        {% if value.get('MALE') %}
        <tr>
            <td {% if value.get('FEMALE') %}rowspan="2"{% endif %}><div class="text-right">{{ key }}</div></td>
            <td><div class="text-right">Male</div></td>
            <td><div class="text-right">${{ value['MALE']|comma_format }}</div></td>
        </tr>
        {% endif %}
        {% if value.get('FEMALE') %}
        <tr>
            {% if not value.get('MALE') %}
            <td><div class="text-right">{{ key }}</div></td>
            {% endif %}
            <td><div class="text-right">Female</div></td>
            <td><div class="text-right">${{ value['FEMALE']|comma_format }}</div></td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Median Income in Davidson County'
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Dollars'
            },
        },
        series: [
            {
                name: 'MALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['MALE'] }},
                            {% endfor %}
                      ]
            },
            {
                name: 'FEMALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['FEMALE'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/medianincome_by_district.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Income Range</th>
        <th>Count</th>
        <th>Median Income</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        {% if value.get('MALE') %}
        <tr>
            <td {% if value.get('FEMALE') %}rowspan="2"{% endif %}><div class="text-right">{{ key }}</div></td>
            <td><div class="text-right">Male</div></td>
            <td><div class="text-right">${{ value['MALE']|comma_format }}</div></td>
        </tr>
        {% endif %}
        {% if value.get('FEMALE') %}
        <tr>
            {% if not value.get('MALE') %}
            <td><div class="text-right">{{ key }}</div></td>
            {% endif %}
            <td><div class="text-right">Female</div></td>
            <td><div class="text-right">${{ value['FEMALE']|comma_format }}</div></td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Median Income in {{ district }}' 
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Dollars'
            },
        },
        series: [
            {
                name: 'MALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['MALE'] }},
                            {% endfor %}
                      ]
            },
            {
                name: 'FEMALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['FEMALE'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/occupation_bygender.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Gender</th>
        <th>Position</th>
        <th>Count</th>
    </thead>
    <tbody>
        {% for key, value in values %}
        {% for job in value %}
        <tr>
            {% if loop.first %}
            <td rowspan="{{ value|length }}"><div class="text-right">{{ key }}</div></td>
            {% endif %} 
            <td><div class="text-right">{{ job }}</div></td>
            <td><div class="text-right">{{ value[job]|comma_format }}</div></td>
        </tr>
        {% endfor %}
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Median Income in Davidson County'
        },
        xAxis: {
            categories: [
            {% for key,value in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Count'
            },
        },
        series: [
            {
                name: 'MALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['MALE'] }},
                            {% endfor %}
                      ]
            },
            {
                name: 'FEMALE',
                      data: [
                            {% for key, value in values %}
                            {{ value['FEMALE'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}

app/templates/census/poverty.html
{% extends 'base.html' %}
{% block content %}
<div id="container" style="width:100%; height:400px;"></div>
{{ results }}
<table class="table table-striped table-bordered table-hover">
    <thead>
        <th>Race</th>
        <th>Total</th>
        <th>Poverty</th>
        <th>% Poverty Race</th>
        <th>% Poverty Overall</th>
        <th>% Population</th>
    </thead>
    <tbody>
        {% for key, result in values %}
        <tr>
            <td>{{ key }}</td>
            <td><div class="text-right">{{ result['ALL']|comma_format }}</div></td>
            <td><div class="text-right">{{ result['POVERTY']|comma_format }}</div></td>
            <td><div class="text-right">{{ result['percent'] }}%</div></td>
            <td><div class="text-right">{{ result['percent_pov_pop'] }}%</div></td>
            <td><div class="text-right">{{ result['percent_pop'] }}%</div></td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
    </tfoot>
</table>
{% endblock %}
{% block extracss %}
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
$(function () { 
    $('#container').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Poverty % by Race in All Districts'
        },
        xAxis: {
            categories: [
            {% for key, result in values %}
            '{{ key }}',
            {% endfor %}
            ]
        },
        yAxis: {
            title: {
                text: 'Percentage'
            },
        },
        series: [
            {
                name: 'Poverty % Race',
                      data: [
                            {% for key, result in values %}
                            {{ result['percent'] }},
                            {% endfor %}
                      ]
            },
            {
                name: 'Poverty % All',
                      data: [
                            {% for key, result in values %}
                            {{ result['percent_pov_pop'] }},
                            {% endfor %}
                      ]
            },
            {
                name: '% Population',
                      data: [
                            {% for key, result in values %}
                            {{ result['percent_pop'] }},
                            {% endfor %}
                      ]
            },
        ]
    });
});
</script>
{% endblock %}