app/surveys/models.py
from app import db


class Surveys(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    desc = db.Column(db.String(1000))
    questions = db.relationship('Questions', backref='surveys', lazy='dynamic')
    active = db.Column(db.Boolean())

    def __init__(self, name, desc, active):
        self.name = name
        self.desc = desc
        self.active = active


class Questions(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(1000))
    survey_id = db.Column(db.Integer, db.ForeignKey('surveys.id'))
    answers = db.relationship('Answers', backref='question', lazy='dynamic')

    def __init__(self, text):
        self.text = text


class Answers(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(1000))
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'))

    def __init__(self, text):
        self.text = text

app/surveys/forms.py
from flask import Flask, request, flash, redirect, url_for, render_template

from flask.ext.wtf import Form
from wtforms import BooleanField, TextField, validators


class SurveyForm(Form):
    name = TextField('Name', [validators.Required()])
    desc = TextField('Description', [validators.Length(max=1000)])
    active = BooleanField('Active', [validators.Required()])


class QuestionForm(Form):
    question = TextField('Question', [validators.Required()])

app/surveys/views.py
from flask import Blueprint, request, render_template, redirect, url_for

from app import db
from app.surveys.models import Surveys, Questions
from app.surveys.forms import SurveyForm, QuestionForm

mod = Blueprint('surveys', __name__, url_prefix='/surveys')


@mod.route('/')
def surveys():
    surveys = Surveys.query.filter(Surveys.active == True).all()
    return render_template('surveys/index.html', surveys=surveys)


@mod.route('/create', methods=['GET', 'POST', ])
def surveys_create():
    form = SurveyForm(request.form)
    if request.method == 'GET':
        return render_template('surveys/create.html', form=form)
    elif request.method == 'POST':
        survey = Surveys(form.name.data, form.desc.data, form.active.data)
        db.session.add(survey)
        db.session.commit()
        return redirect(url_for('surveys.surveys_show', id=survey.id))


@mod.route('/<int:id>')
def surveys_show(id):
    survey = Surveys.query.get(id)
    return render_template('surveys/show.html', survey=survey)


@mod.route('/<int:id>/questions/add/')
def question_add(id):
    if request.method == 'POST':
        question = Questions(request.form['question_text'])
        db.session.add(question)
        db.session.commit()
        return {'success': 'The question was added'}

app/templates/surveys/create.html
<form method="POST" action="{{ url_for('surveys.surveys_create') }}">
    {{ form.name.label }} {{ form.name(size=100) }}<br>
    {{ form.desc.label }} {{ form.desc(size=100) }}<br>
    {{ form.active.label }} {{ form.active }}<br>
    <input type="submit" value="Go">
</form>

app/templates/surveys/create_results.html
{{ form }}

app/templates/surveys/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <table class="table table-striped">
            {% for survey in surveys %}
            <tr>
                <td><a href="{{ url_for('.surveys_show', id=survey.id) }}">{{ survey.name }}</a></td>
            </tr>
            {% endfor %}
        </table>
    </div><!-- /#twowordswrapper -->
{% endblock %}

app/templates/surveys/show.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <h1>Survey: {{ survey.name }}</h1>
        <div class="pull-right">
            <a href="#" class="btn btn-warning">Add Question</a>
        </div>
        <div id="question-form">
            <form method="POST">
                <input type="text" name="question_text">
                <input type="submit" value="Add">
            </form>
        </div>
        <p>{{ survey.desc }}</p>
        {% for question in survey.questions %}
        <div>
            <div class="pull-right">
                <a href="" class="btn btn-warning">Add Answer</a>
            </div>
            {{ question.text }}
            <ul>
            {% for answer in question.answer %}
                <li>{{ answer.text }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endfor %}
        <hr>
    </div><!-- /#twowordswrapper -->
{% endblock %}
{% block extrajs %}
<script type="text/javascript">
    $("#question-form").live("click", function() { 
        $("#question-form").show();
        console.log("test");
        return false;
    });
</script>
{% endblock %}
{% block extracss %}
<style>
    #question-form {
        display: none;
    }
</style>
{% endblock %}