app/census/views.py
from __future__ import division
import operator
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, json, jsonify, current_app)
from flask.ext.login import (login_user, logout_user, current_user)
from flask.ext.principal import Identity, AnonymousIdentity, identity_changed

from sqlalchemy import create_engine
from sqlalchemy.sql import select, func, and_
from sqlalchemy.sql.expression import tuple_

from app import db
from config import SQLALCHEMY_DATABASE_URI
from app.users.models import Users, Roles
from app.census.datahelpers import build_table

mod = Blueprint('census', __name__, url_prefix='/census')


@mod.before_request
def before_request():
    g.conn = create_engine(SQLALCHEMY_DATABASE_URI)
    g.t = None
    g.t = build_table('census')


@mod.route('', methods=['GET', ])
def census():
    income_districts = []
    poverty_districts = []
    medianincome_districts = []
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'INCOME').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        income_districts.append(district)
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'POVERTY').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        poverty_districts.append(district)
    s = select(
        [
            g.t.c.district,
        ], g.t.c.type == 'MEDIANINCOME').distinct().order_by(
                g.t.c.district)
    districts = g.conn.execute(s).fetchall()
    for district in districts:
        medianincome_districts.append(district)
    
    return render_template('census/index.html', income_districts=income_districts, poverty_districts=poverty_districts, medianincome_districts=medianincome_districts)


@mod.route('/test', methods=['GET', ])
def census_test():
    values = {}
    s = select(
        [
            g.t.c.type,
            g.t.c.district,
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], g.t.c.race != 'ALL').group_by(
            g.t.c.type,
            g.t.c.district,
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.type,
                g.t.c.district,
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for result in results:
        type = getattr(result, 'type')
        if not values.get(type):
            values[type] = {}
        district = getattr(result, 'district')
        if not values[type].get(district):
            values[type][district] = {}
        race = getattr(result, 'race')
        if not values[type][district].get(race):
            if getattr(result, 'summed'):
                values[type][district][race] = {}
        if getattr(result, 'summed'):
            values[type][district][race] = getattr(result, 'summed')

    return render_template('census/test.html', values=values)


@mod.route('/poverty_json', methods=['GET', ])
def census_poverty_json():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return_val = {
        'values': values,
        'graph_name': 'Poverty % by Race in All Districts',
        'url': url_for('census.census_poverty_json', _external=True)
    }
    return jsonify(return_val)


@mod.route('/poverty', methods=['GET', ])
def census_proverty():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/poverty.html', values=values)


@mod.route('/poverty_by_district/<district_name>', methods=['GET', ])
def census_proverty_by_district(district_name):
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(and_(
            g.t.c.type == 'POVERTY',
            g.t.c.district == district_name,
            g.t.c.value != 0)).group_by(
                g.t.c.race,
                g.t.c.factor).order_by(
                    g.t.c.race,
                    g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    for value in results:
        race = getattr(value, 'race')
        if not values.get(race):
            values[race] = {}
        factor = getattr(value, 'factor')
        values[race][factor] = value.summed

    bad_keys = []
    for key in values:
        if values[key].get('POVERTY'):
            if values[key].get('ALL'):
                values[key]['percent'] = round((values[key]['POVERTY'] / values[key]['ALL']) * 100, 2)
                values[key]['percent_pov_pop'] = round((values[key]['POVERTY'] / values['ALL']['POVERTY']) * 100, 2)
                values[key]['percent_pop'] = round((values[key]['ALL'] / values['ALL']['ALL']) * 100, 2)
        else:
            if not values[key].get('percent'):
                bad_keys.append(key)

    if bad_keys:
        for key in bad_keys:
            values.pop(key, None)
            values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/poverty_by_district.html', values=values, district=district_name)


@mod.route('/income_by_district/<district_name>', methods=['GET', ])
def census_income_by_district(district_name):
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(
            and_(
                g.t.c.type == 'INCOME',
                g.t.c.district == district_name,
                g.t.c.value != 0,
                g.t.c.race == 'ALL',
            )
        ).group_by(
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    total_value = 0
    for value in results:
        total_value = total_value + getattr(value, 'summed')
        factor = getattr(value, 'factor')
        values[factor] = {'count': value.summed}

    for key in values:
        if total_value > 0:
                values[key]['percent'] = round((values[key]['count'] / values['ALL']['count']) * 100, 2)
    values.pop('ALL', None)
    values = sorted(values.items(), key=operator.itemgetter(1), reverse=True)

    return render_template('census/income_by_district.html', values=values, district=district_name)


@mod.route('/income', methods=['GET', ])
def census_income():
    values = {}
    s = select(
        [
            g.t.c.race,
            g.t.c.factor,
            func.sum(g.t.c.value).label('summed')
        ], ).where(
            and_(
                g.t.c.type == 'INCOME',
                g.t.c.value != 0,
                g.t.c.race == 'ALL',
            )
        ).group_by(
            g.t.c.race,
            g.t.c.factor).order_by(
                g.t.c.race,
                g.t.c.factor)
    results = g.conn.execute(s).fetchall()
    total_value = 0
    for value in results:
        total_value = total_value + getattr(value, 'summed')
        factor = getattr(value, 'factor')
        values[factor] = {'count': value.summed}

    for key in values:
        print
        if total_value > 0:

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>

  <meta charset="utf-8">
  <title> Nashville Human Relations Commission | IncluCivics</title>
  <meta name="description" content=" ">
  <meta name="robot" CONTENT="index,follow">
  <meta name="author" content=" ">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- CSS Files -->
  <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('static', filename='css/navbarfix.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('static', filename='css/bootstrap-responsive.css') }}" rel="stylesheet" media="screen">
  <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" media="screen">

  <!-- Google Web Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Molengo' rel='stylesheet' type='text/css'>

  <!-- Favicon -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!-- JavaScript Files At Bottom For Faster Load -->

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  {% block extracss %}
  {% endblock %}

</head>

<body>

<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> brow-fluidser. Please <a href="http://brow-fluidsehappy.com/">upgrade your brow-fluidser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<!--=============== NAVBAR ===============-->

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="pull-right nav-collapse collapse">
            <ul id="menu-main" class="nav">
              <!--<li><a title="header" href="#top">Top</a></li> -->
              <li><a title="home" href="{{ url_for('handle_splash') }}">Home</a></li>
              <li><a title="census" href="{{ url_for('census.census') }}">Diversity</a></li>
              <li><a title="survey" href="">Inclusion</a></li>
            </ul>
          </div>
        </div>
      </div><!-- /.navbar-inner -->
    </div><!-- /.navbar navbar-inverse navbar-fixed-top -->

    <div id="top">
    </div>

    {% block content %}
    {% endblock %}

<!--=============== FOOTER ===============-->

<br />
    <div class="footerwraper">
    <div class="container">
    <footer>

      <div class="row">
        <div class="span12">
          <h3>
            Site created by:
          </h3>
        </div>
      </div>

      <div class="row">
        <div class="span2">
        </div>
        <div class="span4" id="nh4c">
          <a href="http://hackforchange.org" target="_blank">
              <img src="{{ url_for('static', filename='img/NationalDayOfCivicHacking.jpg')}}" alt="National Day of Civic Hacking" />
          </a>
        </div>
        <div class="span4">
        <div id="h4cn">
          <a href="http://hack4changenash.org" target="_blank">
              <img src="{{ url_for('static', filename='img/NashvilleHackForChange.jpg')}}" alt="Nashville Hack For Change" />
          </a>
        </div>
        </div>
        <div class="span2">
        </div>
      </div>

      <div class="row">
        <div class="span12">
          <h3>
            Brought to you by:
          </h3>
        </div>
      </div>
      <div class="row">
        <div class="span12" id="MHRClogo">
          <a href="http://www.nashville.gov/Human-Relations-Commission.aspx" target="_blank">
              <img src="{{ url_for('static', filename='img/MHRCLogoFinal.jpg' )}}" width="300" height="94" alt="Nashville Human Relations Commission" />
          </a>
        </div>
      </div>

<hr />

      <div class="row">
        <div class="span12">
          <p>
            © 2013 Nashville Human Relations Commission. All rights reserved.
          </p>
        </div>
      </div>

    </footer>
    </div><!-- ./container -->
    <div><!--#footerwraper -->

<!--=============== Google Analytics ===============-->

<!--=============== END ===============-->

<!-- JavaScript Files At Bottom For Faster Load -->

<!-- JavaScript Files At Bottom For Faster Load -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    {% block extrajs %}
    {% endblock %}

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <header>
      <div class="row">
        <div class="span7">
          <h1>Welcome</h1>
          <h3>To Nashville IncluCivics</h3>
<br />
          <strong>
            <h2>
              Nashville:
<br />
              Growing Diversity and Inclusivity
            </h2>
          </strong>
            <p>
              In his 2013 State of the City Address, Mayor Karl Dean, said this: “Successful cities are cities with a high quality of life for people at all points on the economic spectrum. Successful cities are cities that offer opportunity to not just the well-educated, but everyone with the desire to have a better life.”
<br />
<br />
              We know that Nashville and Davidson County is racially, ethnically, and culturally—and growing more so each year—but what demographic statistics don’t tell us is whether our diversity also correlates with an experience of inclusion among the many cultural groups that call Nashville home.
<br/>
<br/>
              As long as mandated or voluntary measures treat cultural diversity as the “problem,” underlying systemic causes for conditions such as poverty, academic disparities, divergent employment outcomes, etc., are not raised or interrogated. The modes and “codes” that create in-groups and out-groups are not identified, explored, challenged, or dismantled. Since it is largely true that “we measure what we value, and what we measure gets done,” the Metro Human Relations Commission wants provide not only easy access to diversity measures, but to put a human face on these statistics by taking the process one step further. As long as mandated or voluntary measures treat cultural diversity as the “problem,” underlying systemic causes for conditions such as poverty, academic disparities, divergent employment outcomes, etc., are not raised or interrogated. The modes and “codes” that create in-groups and out-groups are not identified, explored, challenged, or dismantled. Since it is largely true that “we measure what we value, and what we measure gets done,” the Metro Human Relations Commission wants provide not only easy access to diversity measures, but to put a human face on these statistics by taking the process one step further.
<br/>
<br/>
          <strong>
            <h2>
              The MHRC Solution:
<br/>
            Where Stats Meet Human Experience
            </h2>
          </strong>
<br/>
              Thus, the Metro Human Relations Commission’s IncluCivics. Rather than simply “celebrating” the diversity in our region, the MHRCII seeks to tell the story of where Nashville’s diverse cultural communities are on the journey to inclusion. In Phase One of this project, we offer a centralized system for gathering and reporting key census data, coupled with a self-reporting instrument Inclusivity Index that measures perceptions about social inclusion among Nashville’s diverse racial, ethnic, and cultural communities. This survey will be accessible online, and in print form; it will also be translated into varied languages to ensure the widest range of participation possible.
<br/>
<br/>
              The MHRC IncluCivics application will help generate the needed scorecard, shaped by the authentic voices of our neighbors, Mayor Dean described as being like us, not like us, lost, struggling, and for the young, the old, and everywhere in between who are filled with hope and possibility of Nashville indeed being, “One City for All People.”
            </p>
        </div>
        <div class="span1">
        </div>
        <div class="span4">
          <a href="http://www.nashville.gov/Human-Relations-Commission.aspx" target="_blank">
              <img src="{{ url_for('static', filename='img/MHRCLogoFinal.jpg')}}" alt="Nashville Human Relations Commission" />
          </a>
        </div>
      </div><!-- /.row -->
    </header>
    </div><!-- /.container -->

<!--=============== Diversity, Inclusivity ===============-->

    <div id="twowordswrapper">
    <div class="container">
      <div id="twowords">
      <div class="row">
        <div class="span5" id="diversity">
          <a href="{{ url_for('census.census') }}">
            <h2>Diversity</h2>
          </a>
            <br />
              <p>
                Diversity is the full range of human differences within overarching similarities.  Typically, the word diversity is used to describe quantifiable, observable differences, such as race, age, physical disabilities, skin color, etc.  Diversity is also used as short-hand for those “minority” statuses in U.S. culture that were historically marginalized, or disenfranchised, and that continue to be so in contemporary life and culture.
              </p>
        </div>
        <div class="span2">
          <h2>&#124</h2>
        </div>
        <div class="span5" id="inclusion">
          <a href="">
            <h2>Inclusion</h2>
          </a>
            <br />
              <p>
                Inclusion as a qualitative standard refers to the felt sense of being accepted, safe, affirmed, empowered in an organization’s or community’s political, economic, and social processes.  Inclusive policies and practices are core ways of doing business (rather than “add ons”) that afford all residents equal voice in support of our country’s highest democratic ideals.  Inclusivity engenders belonging because access to power is manifest and a common purpose is forged and “owned” by all.  Inclusivity allows individuals and groups the opportunity to help define and fulfill their roles in a given context, a process that advances mutual understanding and success.
              </p>
        </div>
      </div><!-- /.row -->
    </div><!-- /#twowords -->
    </div><!-- /.container -->
    </div><!-- /#twowordswrapper -->


{% endblock %}